name: library_books
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  animations: ^2.0.11
  flutter_spinkit: ^5.2.1
  dio: ^5.4.3+1
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  logger: ^2.3.0
  animated_text_kit: ^4.2.2
  video_player: ^2.8.6
  permission_handler: ^11.3.1
  animated_loading_indicators: ^1.0.0+4
  flutter_otp_text_field: ^1.1.3+2
  animated_notch_bottom_bar: ^1.0.3
  shadcn_ui: ^0.4.6
  nopsuite_carousel_slider: ^0.0.3
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/Splash_screen.mp4
      - assets/images/
      - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
